-- ================================
-- TABELA USUARIO
-- ================================
CREATE TABLE USUARIO (
    ID BIGINT PRIMARY KEY,
    CARGO VARCHAR(50) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(14) UNIQUE,
    CONSTRAINT CHK_CARGO CHECK (
        CARGO IN (
            'ADMINISTRADOR',
            'GERENTE',
            'ATENDENTE',
            'MECANICO',
            'AUXILIAR',
            'ENTREGADOR'
        )
    )
);

-- ================================
-- TABELA PATIO
-- ================================
CREATE TABLE PATIO (
    ID_PATIO BIGINT IDENTITY(1,1) PRIMARY KEY,
    LOCALIZACAO VARCHAR(255) NOT NULL,
    QUANTIDADE_VAGAS INT,
    CADASTRO_POR BIGINT,
    CONSTRAINT FK_PATIO_USUARIO FOREIGN KEY (CADASTRO_POR)
        REFERENCES USUARIO(ID)
);

-- ================================
-- TABELA MOTO
-- ================================
CREATE TABLE MOTO (
    ID BIGINT PRIMARY KEY,
    MODELO VARCHAR(50) NOT NULL,
    ANO INT,
    COR VARCHAR(50),
    STATUS VARCHAR(50),
    CADASTRO_POR BIGINT,
    PATIO_ID BIGINT,
    PLACA VARCHAR(10) NOT NULL,
    CONSTRAINT FK_MOTO_USUARIO FOREIGN KEY (CADASTRO_POR)
        REFERENCES USUARIO(ID)
        ON DELETE SET NULL,
    CONSTRAINT FK_MOTO_PATIO FOREIGN KEY (PATIO_ID)
        REFERENCES PATIO(ID_PATIO),
    CONSTRAINT CHK_MODELO CHECK (MODELO IN ('MOTTU_POP','MOTTU_E','MOTTU_SPORT')),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('DISPONIVEL','RESERVADA','EM_MANUTENCAO','OUTROS'))
);

-- ================================
-- SEQUENCES (SQL Server / Azure)
-- ================================
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MOTO START WITH 1 INCREMENT BY 1;

